
<?php
$icons = [
     ['Search Button Icon', 'fas fa-magnifying-glass-arrows-rotate'],
    ['Facebook Icon', 'fas fa-facebook">'],
    ['Youtube Icon', 'fas fa-youtube'],
    ['Instagram Icon', 'fas fa-instagram'],
    ['Linkedin Icon', 'fas fa-linkedin'],
    ['Whatsapp Icon', 'fas fa-whatsapp'],
    ['Twitter Icon', 'fas fa-square-x-twitter'],        
    ['Wifi Icon', 'fas fa-wifi'],
    ['Mobile Icon', "fas fa-mobile-button"],
    ['Credit Card Icon', 'fas fa-credit-card'],
    ['Chart-line Icon', 'fas fa-chart-line'],
    ['Bolt Icon', 'fas fa-bolt'],
    ['Door Open Icon', "fas fa-door-open"],    
    ['Phone Icon', "fas fa-phone"],
    ['Email Icon', 'fas fa-envelope-dot'],
    ['Right Arrow Icon', 'fas fa-chevron-right'],
    ['Plus Icon', 'fas fa-plus'],    
    ['Email Icon', 'fas fa-envelope-circle-check'],
    ['City Icon', 'fas fa-city'],
    ['Home Icon', 'fas fa-building-user'],    
    ['Circle With A Tick Icon', 'fas fa-circle-check'],    
    ['Downloads Icon', 'fas fa-file-arrow-down'],
    ['User Icon', 'fas fa-user'],   
    ['Awards Icon', 'fas fa-award'],    
    ['Down Arrow Icon', 'fas  fa-chevron-down'],
    ['Right Arrow Icon', 'fas  fa-chevron-right'],    
    ['Form Icon', 'fas  fa-wpforms'],    
    ['Message Icon', 'fas fa-message'],    
    ['Upload Icon', 'fas fa-cloud-arrow-up'],

];
